#ifndef __VALHALLA_SIF_VERSION_H__
#define __VALHALLA_SIF_VERSION_H__

//some version info
#define VALHALLA_SIF_VERSION_MAJOR 1
#define VALHALLA_SIF_VERSION_MINOR 0
#define VALHALLA_SIF_VERSION_PATCH 0

#endif //__VALHALLA_SIF_VERSION_H__
