coverage:
  ignore:
    - third_party/.*
    # test code
    - test/.*
    # executables (not library code)
    - src/valhalla_*
    - src/mjolnir/valhalla_*
    # bindings (separate test suites)
    - src/bindings/.*

comment: off
