#ifndef __VALHALLA_SKADI_VERSION_H__
#define __VALHALLA_SKADI_VERSION_H__

//some version info
#define VALHALLA_SKADI_VERSION_MAJOR 1
#define VALHALLA_SKADI_VERSION_MINOR 0
#define VALHALLA_SKADI_VERSION_PATCH 0

#endif //__VALHALLA_SKADI_VERSION_H__
