#ifndef __VALHALLA_LOKI_VERSION_H__
#define __VALHALLA_LOKI_VERSION_H__

//some version info
#define VALHALLA_LOKI_VERSION_MAJOR 1
#define VALHALLA_LOKI_VERSION_MINOR 0
#define VALHALLA_LOKI_VERSION_PATCH 0

#endif //__VALHALLA_LOKI_VERSION_H__
