#!/usr/bin/env python3
"""
Prepend a "machine-generated" banner to a .pyi file. Idempotent: re-runs are
no-ops once the header is in place. Called from CMake right after
nanobind_add_stub finishes generating each stub.
"""

import sys
from pathlib import Path

HEADER_MARK = "# AUTO-GENERATED"
HEADER = """\
# AUTO-GENERATED by nanobind_add_stub from the matching C++ binding.
# Do not edit by hand — your changes will be overwritten on the next build.
# See src/bindings/python/README.md ("Type stubs") for the regeneration workflow.

"""


def main(path: str) -> None:
    pyi = Path(path)
    text = pyi.read_text()
    # Strip an existing banner so changes to HEADER propagate: the leading run
    # of '#' comment lines plus one trailing blank separator.
    if text.lstrip().startswith(HEADER_MARK):
        lines = text.splitlines(keepends=True)
        i = 0
        while i < len(lines) and lines[i].startswith("#"):
            i += 1
        if i < len(lines) and lines[i].strip() == "":
            i += 1
        text = "".join(lines[i:])
    new_text = HEADER + text.lstrip("\n")
    if pyi.read_text() != new_text:
        pyi.write_text(new_text)


if __name__ == "__main__":
    main(sys.argv[1])
