FROM ubuntu:20.04

ADD install-shared-deps.sh .
RUN bash ./install-shared-deps.sh

RUN apt-get update -y && apt-get install -y python3-pip && pip3 install conan

# set paths
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
ENV LD_LIBRARY_PATH /usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib32:/usr/lib32
