#ifndef __VALHALLA_TOOLS_VERSION_H__
#define __VALHALLA_TOOLS_VERSION_H__

//some version info
#define VALHALLA_TOOLS_VERSION_MAJOR 1
#define VALHALLA_TOOLS_VERSION_MINOR 0
#define VALHALLA_TOOLS_VERSION_PATCH 0

#endif //__VALHALLA_TOOLS_VERSION_H__
