// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: incidents.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_incidents_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_incidents_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_incidents_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_incidents_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
namespace valhalla {
class IncidentsTile;
struct IncidentsTileDefaultTypeInternal;
extern IncidentsTileDefaultTypeInternal _IncidentsTile_default_instance_;
class IncidentsTile_Location;
struct IncidentsTile_LocationDefaultTypeInternal;
extern IncidentsTile_LocationDefaultTypeInternal _IncidentsTile_Location_default_instance_;
class IncidentsTile_Metadata;
struct IncidentsTile_MetadataDefaultTypeInternal;
extern IncidentsTile_MetadataDefaultTypeInternal _IncidentsTile_Metadata_default_instance_;
class IncidentsTile_Metadata_Congestion;
struct IncidentsTile_Metadata_CongestionDefaultTypeInternal;
extern IncidentsTile_Metadata_CongestionDefaultTypeInternal _IncidentsTile_Metadata_Congestion_default_instance_;
}  // namespace valhalla
PROTOBUF_NAMESPACE_OPEN
template<> ::valhalla::IncidentsTile* Arena::CreateMaybeMessage<::valhalla::IncidentsTile>(Arena*);
template<> ::valhalla::IncidentsTile_Location* Arena::CreateMaybeMessage<::valhalla::IncidentsTile_Location>(Arena*);
template<> ::valhalla::IncidentsTile_Metadata* Arena::CreateMaybeMessage<::valhalla::IncidentsTile_Metadata>(Arena*);
template<> ::valhalla::IncidentsTile_Metadata_Congestion* Arena::CreateMaybeMessage<::valhalla::IncidentsTile_Metadata_Congestion>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace valhalla {

enum IncidentsTile_Metadata_Type : int {
  IncidentsTile_Metadata_Type_ACCIDENT = 0,
  IncidentsTile_Metadata_Type_CONGESTION = 1,
  IncidentsTile_Metadata_Type_CONSTRUCTION = 2,
  IncidentsTile_Metadata_Type_DISABLED_VEHICLE = 3,
  IncidentsTile_Metadata_Type_LANE_RESTRICTION = 4,
  IncidentsTile_Metadata_Type_MASS_TRANSIT = 5,
  IncidentsTile_Metadata_Type_MISCELLANEOUS = 6,
  IncidentsTile_Metadata_Type_OTHER_NEWS = 7,
  IncidentsTile_Metadata_Type_PLANNED_EVENT = 8,
  IncidentsTile_Metadata_Type_ROAD_CLOSURE = 9,
  IncidentsTile_Metadata_Type_ROAD_HAZARD = 10,
  IncidentsTile_Metadata_Type_WEATHER = 11,
  IncidentsTile_Metadata_Type_IncidentsTile_Metadata_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  IncidentsTile_Metadata_Type_IncidentsTile_Metadata_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool IncidentsTile_Metadata_Type_IsValid(int value);
constexpr IncidentsTile_Metadata_Type IncidentsTile_Metadata_Type_Type_MIN = IncidentsTile_Metadata_Type_ACCIDENT;
constexpr IncidentsTile_Metadata_Type IncidentsTile_Metadata_Type_Type_MAX = IncidentsTile_Metadata_Type_WEATHER;
constexpr int IncidentsTile_Metadata_Type_Type_ARRAYSIZE = IncidentsTile_Metadata_Type_Type_MAX + 1;

const std::string& IncidentsTile_Metadata_Type_Name(IncidentsTile_Metadata_Type value);
template<typename T>
inline const std::string& IncidentsTile_Metadata_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, IncidentsTile_Metadata_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function IncidentsTile_Metadata_Type_Name.");
  return IncidentsTile_Metadata_Type_Name(static_cast<IncidentsTile_Metadata_Type>(enum_t_value));
}
bool IncidentsTile_Metadata_Type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, IncidentsTile_Metadata_Type* value);
enum IncidentsTile_Metadata_Impact : int {
  IncidentsTile_Metadata_Impact_UNKNOWN = 0,
  IncidentsTile_Metadata_Impact_CRITICAL = 1,
  IncidentsTile_Metadata_Impact_MAJOR = 2,
  IncidentsTile_Metadata_Impact_MINOR = 3,
  IncidentsTile_Metadata_Impact_LOW = 4,
  IncidentsTile_Metadata_Impact_IncidentsTile_Metadata_Impact_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  IncidentsTile_Metadata_Impact_IncidentsTile_Metadata_Impact_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool IncidentsTile_Metadata_Impact_IsValid(int value);
constexpr IncidentsTile_Metadata_Impact IncidentsTile_Metadata_Impact_Impact_MIN = IncidentsTile_Metadata_Impact_UNKNOWN;
constexpr IncidentsTile_Metadata_Impact IncidentsTile_Metadata_Impact_Impact_MAX = IncidentsTile_Metadata_Impact_LOW;
constexpr int IncidentsTile_Metadata_Impact_Impact_ARRAYSIZE = IncidentsTile_Metadata_Impact_Impact_MAX + 1;

const std::string& IncidentsTile_Metadata_Impact_Name(IncidentsTile_Metadata_Impact value);
template<typename T>
inline const std::string& IncidentsTile_Metadata_Impact_Name(T enum_t_value) {
  static_assert(::std::is_same<T, IncidentsTile_Metadata_Impact>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function IncidentsTile_Metadata_Impact_Name.");
  return IncidentsTile_Metadata_Impact_Name(static_cast<IncidentsTile_Metadata_Impact>(enum_t_value));
}
bool IncidentsTile_Metadata_Impact_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, IncidentsTile_Metadata_Impact* value);
// ===================================================================

class IncidentsTile_Location final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:valhalla.IncidentsTile.Location) */ {
 public:
  inline IncidentsTile_Location() : IncidentsTile_Location(nullptr) {}
  ~IncidentsTile_Location() override;
  explicit constexpr IncidentsTile_Location(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IncidentsTile_Location(const IncidentsTile_Location& from);
  IncidentsTile_Location(IncidentsTile_Location&& from) noexcept
    : IncidentsTile_Location() {
    *this = ::std::move(from);
  }

  inline IncidentsTile_Location& operator=(const IncidentsTile_Location& from) {
    CopyFrom(from);
    return *this;
  }
  inline IncidentsTile_Location& operator=(IncidentsTile_Location&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const IncidentsTile_Location& default_instance() {
    return *internal_default_instance();
  }
  static inline const IncidentsTile_Location* internal_default_instance() {
    return reinterpret_cast<const IncidentsTile_Location*>(
               &_IncidentsTile_Location_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IncidentsTile_Location& a, IncidentsTile_Location& b) {
    a.Swap(&b);
  }
  inline void Swap(IncidentsTile_Location* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IncidentsTile_Location* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IncidentsTile_Location* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IncidentsTile_Location>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const IncidentsTile_Location& from);
  void MergeFrom(const IncidentsTile_Location& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IncidentsTile_Location* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "valhalla.IncidentsTile.Location";
  }
  protected:
  explicit IncidentsTile_Location(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEdgeIndexFieldNumber = 1,
    kStartOffsetFieldNumber = 2,
    kEndOffsetFieldNumber = 3,
    kMetadataIndexFieldNumber = 4,
  };
  // uint32 edge_index = 1;
  void clear_edge_index();
  uint32_t edge_index() const;
  void set_edge_index(uint32_t value);
  private:
  uint32_t _internal_edge_index() const;
  void _internal_set_edge_index(uint32_t value);
  public:

  // float start_offset = 2;
  void clear_start_offset();
  float start_offset() const;
  void set_start_offset(float value);
  private:
  float _internal_start_offset() const;
  void _internal_set_start_offset(float value);
  public:

  // float end_offset = 3;
  void clear_end_offset();
  float end_offset() const;
  void set_end_offset(float value);
  private:
  float _internal_end_offset() const;
  void _internal_set_end_offset(float value);
  public:

  // uint32 metadata_index = 4;
  void clear_metadata_index();
  uint32_t metadata_index() const;
  void set_metadata_index(uint32_t value);
  private:
  uint32_t _internal_metadata_index() const;
  void _internal_set_metadata_index(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:valhalla.IncidentsTile.Location)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t edge_index_;
  float start_offset_;
  float end_offset_;
  uint32_t metadata_index_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_incidents_2eproto;
};
// -------------------------------------------------------------------

class IncidentsTile_Metadata_Congestion final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:valhalla.IncidentsTile.Metadata.Congestion) */ {
 public:
  inline IncidentsTile_Metadata_Congestion() : IncidentsTile_Metadata_Congestion(nullptr) {}
  ~IncidentsTile_Metadata_Congestion() override;
  explicit constexpr IncidentsTile_Metadata_Congestion(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IncidentsTile_Metadata_Congestion(const IncidentsTile_Metadata_Congestion& from);
  IncidentsTile_Metadata_Congestion(IncidentsTile_Metadata_Congestion&& from) noexcept
    : IncidentsTile_Metadata_Congestion() {
    *this = ::std::move(from);
  }

  inline IncidentsTile_Metadata_Congestion& operator=(const IncidentsTile_Metadata_Congestion& from) {
    CopyFrom(from);
    return *this;
  }
  inline IncidentsTile_Metadata_Congestion& operator=(IncidentsTile_Metadata_Congestion&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const IncidentsTile_Metadata_Congestion& default_instance() {
    return *internal_default_instance();
  }
  static inline const IncidentsTile_Metadata_Congestion* internal_default_instance() {
    return reinterpret_cast<const IncidentsTile_Metadata_Congestion*>(
               &_IncidentsTile_Metadata_Congestion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(IncidentsTile_Metadata_Congestion& a, IncidentsTile_Metadata_Congestion& b) {
    a.Swap(&b);
  }
  inline void Swap(IncidentsTile_Metadata_Congestion* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IncidentsTile_Metadata_Congestion* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IncidentsTile_Metadata_Congestion* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IncidentsTile_Metadata_Congestion>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const IncidentsTile_Metadata_Congestion& from);
  void MergeFrom(const IncidentsTile_Metadata_Congestion& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IncidentsTile_Metadata_Congestion* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "valhalla.IncidentsTile.Metadata.Congestion";
  }
  protected:
  explicit IncidentsTile_Metadata_Congestion(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // uint32 value = 1;
  void clear_value();
  uint32_t value() const;
  void set_value(uint32_t value);
  private:
  uint32_t _internal_value() const;
  void _internal_set_value(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:valhalla.IncidentsTile.Metadata.Congestion)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_incidents_2eproto;
};
// -------------------------------------------------------------------

class IncidentsTile_Metadata final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:valhalla.IncidentsTile.Metadata) */ {
 public:
  inline IncidentsTile_Metadata() : IncidentsTile_Metadata(nullptr) {}
  ~IncidentsTile_Metadata() override;
  explicit constexpr IncidentsTile_Metadata(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IncidentsTile_Metadata(const IncidentsTile_Metadata& from);
  IncidentsTile_Metadata(IncidentsTile_Metadata&& from) noexcept
    : IncidentsTile_Metadata() {
    *this = ::std::move(from);
  }

  inline IncidentsTile_Metadata& operator=(const IncidentsTile_Metadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline IncidentsTile_Metadata& operator=(IncidentsTile_Metadata&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const IncidentsTile_Metadata& default_instance() {
    return *internal_default_instance();
  }
  static inline const IncidentsTile_Metadata* internal_default_instance() {
    return reinterpret_cast<const IncidentsTile_Metadata*>(
               &_IncidentsTile_Metadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(IncidentsTile_Metadata& a, IncidentsTile_Metadata& b) {
    a.Swap(&b);
  }
  inline void Swap(IncidentsTile_Metadata* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IncidentsTile_Metadata* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IncidentsTile_Metadata* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IncidentsTile_Metadata>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const IncidentsTile_Metadata& from);
  void MergeFrom(const IncidentsTile_Metadata& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IncidentsTile_Metadata* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "valhalla.IncidentsTile.Metadata";
  }
  protected:
  explicit IncidentsTile_Metadata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef IncidentsTile_Metadata_Congestion Congestion;

  typedef IncidentsTile_Metadata_Type Type;
  static constexpr Type ACCIDENT =
    IncidentsTile_Metadata_Type_ACCIDENT;
  static constexpr Type CONGESTION =
    IncidentsTile_Metadata_Type_CONGESTION;
  static constexpr Type CONSTRUCTION =
    IncidentsTile_Metadata_Type_CONSTRUCTION;
  static constexpr Type DISABLED_VEHICLE =
    IncidentsTile_Metadata_Type_DISABLED_VEHICLE;
  static constexpr Type LANE_RESTRICTION =
    IncidentsTile_Metadata_Type_LANE_RESTRICTION;
  static constexpr Type MASS_TRANSIT =
    IncidentsTile_Metadata_Type_MASS_TRANSIT;
  static constexpr Type MISCELLANEOUS =
    IncidentsTile_Metadata_Type_MISCELLANEOUS;
  static constexpr Type OTHER_NEWS =
    IncidentsTile_Metadata_Type_OTHER_NEWS;
  static constexpr Type PLANNED_EVENT =
    IncidentsTile_Metadata_Type_PLANNED_EVENT;
  static constexpr Type ROAD_CLOSURE =
    IncidentsTile_Metadata_Type_ROAD_CLOSURE;
  static constexpr Type ROAD_HAZARD =
    IncidentsTile_Metadata_Type_ROAD_HAZARD;
  static constexpr Type WEATHER =
    IncidentsTile_Metadata_Type_WEATHER;
  static inline bool Type_IsValid(int value) {
    return IncidentsTile_Metadata_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    IncidentsTile_Metadata_Type_Type_MIN;
  static constexpr Type Type_MAX =
    IncidentsTile_Metadata_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    IncidentsTile_Metadata_Type_Type_ARRAYSIZE;
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return IncidentsTile_Metadata_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Type* value) {
    return IncidentsTile_Metadata_Type_Parse(name, value);
  }

  typedef IncidentsTile_Metadata_Impact Impact;
  static constexpr Impact UNKNOWN =
    IncidentsTile_Metadata_Impact_UNKNOWN;
  static constexpr Impact CRITICAL =
    IncidentsTile_Metadata_Impact_CRITICAL;
  static constexpr Impact MAJOR =
    IncidentsTile_Metadata_Impact_MAJOR;
  static constexpr Impact MINOR =
    IncidentsTile_Metadata_Impact_MINOR;
  static constexpr Impact LOW =
    IncidentsTile_Metadata_Impact_LOW;
  static inline bool Impact_IsValid(int value) {
    return IncidentsTile_Metadata_Impact_IsValid(value);
  }
  static constexpr Impact Impact_MIN =
    IncidentsTile_Metadata_Impact_Impact_MIN;
  static constexpr Impact Impact_MAX =
    IncidentsTile_Metadata_Impact_Impact_MAX;
  static constexpr int Impact_ARRAYSIZE =
    IncidentsTile_Metadata_Impact_Impact_ARRAYSIZE;
  template<typename T>
  static inline const std::string& Impact_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Impact>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Impact_Name.");
    return IncidentsTile_Metadata_Impact_Name(enum_t_value);
  }
  static inline bool Impact_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Impact* value) {
    return IncidentsTile_Metadata_Impact_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kAlertcCodesFieldNumber = 2,
    kLanesBlockedFieldNumber = 12,
    kDescriptionFieldNumber = 3,
    kSubTypeFieldNumber = 4,
    kSubTypeDescriptionFieldNumber = 5,
    kLongDescriptionFieldNumber = 14,
    kClearLanesFieldNumber = 15,
    kIso31661Alpha2FieldNumber = 129,
    kIso31661Alpha3FieldNumber = 130,
    kCongestionFieldNumber = 11,
    kTypeFieldNumber = 1,
    kImpactFieldNumber = 9,
    kStartTimeFieldNumber = 6,
    kEndTimeFieldNumber = 7,
    kCreationTimeFieldNumber = 13,
    kRoadClosedFieldNumber = 10,
    kLengthFieldNumber = 17,
    kNumLanesBlockedFieldNumber = 16,
    kIdFieldNumber = 128,
  };
  // repeated uint32 alertc_codes = 2;
  int alertc_codes_size() const;
  private:
  int _internal_alertc_codes_size() const;
  public:
  void clear_alertc_codes();
  private:
  uint32_t _internal_alertc_codes(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_alertc_codes() const;
  void _internal_add_alertc_codes(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_alertc_codes();
  public:
  uint32_t alertc_codes(int index) const;
  void set_alertc_codes(int index, uint32_t value);
  void add_alertc_codes(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      alertc_codes() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_alertc_codes();

  // repeated string lanes_blocked = 12;
  int lanes_blocked_size() const;
  private:
  int _internal_lanes_blocked_size() const;
  public:
  void clear_lanes_blocked();
  const std::string& lanes_blocked(int index) const;
  std::string* mutable_lanes_blocked(int index);
  void set_lanes_blocked(int index, const std::string& value);
  void set_lanes_blocked(int index, std::string&& value);
  void set_lanes_blocked(int index, const char* value);
  void set_lanes_blocked(int index, const char* value, size_t size);
  std::string* add_lanes_blocked();
  void add_lanes_blocked(const std::string& value);
  void add_lanes_blocked(std::string&& value);
  void add_lanes_blocked(const char* value);
  void add_lanes_blocked(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& lanes_blocked() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_lanes_blocked();
  private:
  const std::string& _internal_lanes_blocked(int index) const;
  std::string* _internal_add_lanes_blocked();
  public:

  // string description = 3;
  void clear_description();
  const std::string& description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_description();
  PROTOBUF_NODISCARD std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // string sub_type = 4;
  void clear_sub_type();
  const std::string& sub_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sub_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sub_type();
  PROTOBUF_NODISCARD std::string* release_sub_type();
  void set_allocated_sub_type(std::string* sub_type);
  private:
  const std::string& _internal_sub_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sub_type(const std::string& value);
  std::string* _internal_mutable_sub_type();
  public:

  // string sub_type_description = 5;
  void clear_sub_type_description();
  const std::string& sub_type_description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sub_type_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sub_type_description();
  PROTOBUF_NODISCARD std::string* release_sub_type_description();
  void set_allocated_sub_type_description(std::string* sub_type_description);
  private:
  const std::string& _internal_sub_type_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sub_type_description(const std::string& value);
  std::string* _internal_mutable_sub_type_description();
  public:

  // string long_description = 14;
  void clear_long_description();
  const std::string& long_description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_long_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_long_description();
  PROTOBUF_NODISCARD std::string* release_long_description();
  void set_allocated_long_description(std::string* long_description);
  private:
  const std::string& _internal_long_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_long_description(const std::string& value);
  std::string* _internal_mutable_long_description();
  public:

  // string clear_lanes = 15;
  void clear_clear_lanes();
  const std::string& clear_lanes() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_clear_lanes(ArgT0&& arg0, ArgT... args);
  std::string* mutable_clear_lanes();
  PROTOBUF_NODISCARD std::string* release_clear_lanes();
  void set_allocated_clear_lanes(std::string* clear_lanes);
  private:
  const std::string& _internal_clear_lanes() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_clear_lanes(const std::string& value);
  std::string* _internal_mutable_clear_lanes();
  public:

  // string iso_3166_1_alpha2 = 129;
  void clear_iso_3166_1_alpha2();
  const std::string& iso_3166_1_alpha2() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_iso_3166_1_alpha2(ArgT0&& arg0, ArgT... args);
  std::string* mutable_iso_3166_1_alpha2();
  PROTOBUF_NODISCARD std::string* release_iso_3166_1_alpha2();
  void set_allocated_iso_3166_1_alpha2(std::string* iso_3166_1_alpha2);
  private:
  const std::string& _internal_iso_3166_1_alpha2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_iso_3166_1_alpha2(const std::string& value);
  std::string* _internal_mutable_iso_3166_1_alpha2();
  public:

  // string iso_3166_1_alpha3 = 130;
  void clear_iso_3166_1_alpha3();
  const std::string& iso_3166_1_alpha3() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_iso_3166_1_alpha3(ArgT0&& arg0, ArgT... args);
  std::string* mutable_iso_3166_1_alpha3();
  PROTOBUF_NODISCARD std::string* release_iso_3166_1_alpha3();
  void set_allocated_iso_3166_1_alpha3(std::string* iso_3166_1_alpha3);
  private:
  const std::string& _internal_iso_3166_1_alpha3() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_iso_3166_1_alpha3(const std::string& value);
  std::string* _internal_mutable_iso_3166_1_alpha3();
  public:

  // .valhalla.IncidentsTile.Metadata.Congestion congestion = 11;
  bool has_congestion() const;
  private:
  bool _internal_has_congestion() const;
  public:
  void clear_congestion();
  const ::valhalla::IncidentsTile_Metadata_Congestion& congestion() const;
  PROTOBUF_NODISCARD ::valhalla::IncidentsTile_Metadata_Congestion* release_congestion();
  ::valhalla::IncidentsTile_Metadata_Congestion* mutable_congestion();
  void set_allocated_congestion(::valhalla::IncidentsTile_Metadata_Congestion* congestion);
  private:
  const ::valhalla::IncidentsTile_Metadata_Congestion& _internal_congestion() const;
  ::valhalla::IncidentsTile_Metadata_Congestion* _internal_mutable_congestion();
  public:
  void unsafe_arena_set_allocated_congestion(
      ::valhalla::IncidentsTile_Metadata_Congestion* congestion);
  ::valhalla::IncidentsTile_Metadata_Congestion* unsafe_arena_release_congestion();

  // .valhalla.IncidentsTile.Metadata.Type type = 1;
  void clear_type();
  ::valhalla::IncidentsTile_Metadata_Type type() const;
  void set_type(::valhalla::IncidentsTile_Metadata_Type value);
  private:
  ::valhalla::IncidentsTile_Metadata_Type _internal_type() const;
  void _internal_set_type(::valhalla::IncidentsTile_Metadata_Type value);
  public:

  // .valhalla.IncidentsTile.Metadata.Impact impact = 9;
  void clear_impact();
  ::valhalla::IncidentsTile_Metadata_Impact impact() const;
  void set_impact(::valhalla::IncidentsTile_Metadata_Impact value);
  private:
  ::valhalla::IncidentsTile_Metadata_Impact _internal_impact() const;
  void _internal_set_impact(::valhalla::IncidentsTile_Metadata_Impact value);
  public:

  // uint64 start_time = 6;
  void clear_start_time();
  uint64_t start_time() const;
  void set_start_time(uint64_t value);
  private:
  uint64_t _internal_start_time() const;
  void _internal_set_start_time(uint64_t value);
  public:

  // uint64 end_time = 7;
  void clear_end_time();
  uint64_t end_time() const;
  void set_end_time(uint64_t value);
  private:
  uint64_t _internal_end_time() const;
  void _internal_set_end_time(uint64_t value);
  public:

  // uint64 creation_time = 13;
  void clear_creation_time();
  uint64_t creation_time() const;
  void set_creation_time(uint64_t value);
  private:
  uint64_t _internal_creation_time() const;
  void _internal_set_creation_time(uint64_t value);
  public:

  // bool road_closed = 10;
  void clear_road_closed();
  bool road_closed() const;
  void set_road_closed(bool value);
  private:
  bool _internal_road_closed() const;
  void _internal_set_road_closed(bool value);
  public:

  // uint32 length = 17;
  void clear_length();
  uint32_t length() const;
  void set_length(uint32_t value);
  private:
  uint32_t _internal_length() const;
  void _internal_set_length(uint32_t value);
  public:

  // uint64 num_lanes_blocked = 16;
  void clear_num_lanes_blocked();
  uint64_t num_lanes_blocked() const;
  void set_num_lanes_blocked(uint64_t value);
  private:
  uint64_t _internal_num_lanes_blocked() const;
  void _internal_set_num_lanes_blocked(uint64_t value);
  public:

  // uint64 id = 128;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:valhalla.IncidentsTile.Metadata)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > alertc_codes_;
  mutable std::atomic<int> _alertc_codes_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> lanes_blocked_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sub_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sub_type_description_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr long_description_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr clear_lanes_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr iso_3166_1_alpha2_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr iso_3166_1_alpha3_;
  ::valhalla::IncidentsTile_Metadata_Congestion* congestion_;
  int type_;
  int impact_;
  uint64_t start_time_;
  uint64_t end_time_;
  uint64_t creation_time_;
  bool road_closed_;
  uint32_t length_;
  uint64_t num_lanes_blocked_;
  uint64_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_incidents_2eproto;
};
// -------------------------------------------------------------------

class IncidentsTile final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:valhalla.IncidentsTile) */ {
 public:
  inline IncidentsTile() : IncidentsTile(nullptr) {}
  ~IncidentsTile() override;
  explicit constexpr IncidentsTile(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IncidentsTile(const IncidentsTile& from);
  IncidentsTile(IncidentsTile&& from) noexcept
    : IncidentsTile() {
    *this = ::std::move(from);
  }

  inline IncidentsTile& operator=(const IncidentsTile& from) {
    CopyFrom(from);
    return *this;
  }
  inline IncidentsTile& operator=(IncidentsTile&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const IncidentsTile& default_instance() {
    return *internal_default_instance();
  }
  static inline const IncidentsTile* internal_default_instance() {
    return reinterpret_cast<const IncidentsTile*>(
               &_IncidentsTile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(IncidentsTile& a, IncidentsTile& b) {
    a.Swap(&b);
  }
  inline void Swap(IncidentsTile* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IncidentsTile* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IncidentsTile* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IncidentsTile>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const IncidentsTile& from);
  void MergeFrom(const IncidentsTile& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IncidentsTile* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "valhalla.IncidentsTile";
  }
  protected:
  explicit IncidentsTile(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef IncidentsTile_Location Location;
  typedef IncidentsTile_Metadata Metadata;

  // accessors -------------------------------------------------------

  enum : int {
    kLocationsFieldNumber = 1,
    kMetadataFieldNumber = 2,
  };
  // repeated .valhalla.IncidentsTile.Location locations = 1;
  int locations_size() const;
  private:
  int _internal_locations_size() const;
  public:
  void clear_locations();
  ::valhalla::IncidentsTile_Location* mutable_locations(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::valhalla::IncidentsTile_Location >*
      mutable_locations();
  private:
  const ::valhalla::IncidentsTile_Location& _internal_locations(int index) const;
  ::valhalla::IncidentsTile_Location* _internal_add_locations();
  public:
  const ::valhalla::IncidentsTile_Location& locations(int index) const;
  ::valhalla::IncidentsTile_Location* add_locations();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::valhalla::IncidentsTile_Location >&
      locations() const;

  // repeated .valhalla.IncidentsTile.Metadata metadata = 2;
  int metadata_size() const;
  private:
  int _internal_metadata_size() const;
  public:
  void clear_metadata();
  ::valhalla::IncidentsTile_Metadata* mutable_metadata(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::valhalla::IncidentsTile_Metadata >*
      mutable_metadata();
  private:
  const ::valhalla::IncidentsTile_Metadata& _internal_metadata(int index) const;
  ::valhalla::IncidentsTile_Metadata* _internal_add_metadata();
  public:
  const ::valhalla::IncidentsTile_Metadata& metadata(int index) const;
  ::valhalla::IncidentsTile_Metadata* add_metadata();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::valhalla::IncidentsTile_Metadata >&
      metadata() const;

  // @@protoc_insertion_point(class_scope:valhalla.IncidentsTile)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::valhalla::IncidentsTile_Location > locations_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::valhalla::IncidentsTile_Metadata > metadata_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_incidents_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IncidentsTile_Location

// uint32 edge_index = 1;
inline void IncidentsTile_Location::clear_edge_index() {
  edge_index_ = 0u;
}
inline uint32_t IncidentsTile_Location::_internal_edge_index() const {
  return edge_index_;
}
inline uint32_t IncidentsTile_Location::edge_index() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Location.edge_index)
  return _internal_edge_index();
}
inline void IncidentsTile_Location::_internal_set_edge_index(uint32_t value) {
  
  edge_index_ = value;
}
inline void IncidentsTile_Location::set_edge_index(uint32_t value) {
  _internal_set_edge_index(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Location.edge_index)
}

// float start_offset = 2;
inline void IncidentsTile_Location::clear_start_offset() {
  start_offset_ = 0;
}
inline float IncidentsTile_Location::_internal_start_offset() const {
  return start_offset_;
}
inline float IncidentsTile_Location::start_offset() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Location.start_offset)
  return _internal_start_offset();
}
inline void IncidentsTile_Location::_internal_set_start_offset(float value) {
  
  start_offset_ = value;
}
inline void IncidentsTile_Location::set_start_offset(float value) {
  _internal_set_start_offset(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Location.start_offset)
}

// float end_offset = 3;
inline void IncidentsTile_Location::clear_end_offset() {
  end_offset_ = 0;
}
inline float IncidentsTile_Location::_internal_end_offset() const {
  return end_offset_;
}
inline float IncidentsTile_Location::end_offset() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Location.end_offset)
  return _internal_end_offset();
}
inline void IncidentsTile_Location::_internal_set_end_offset(float value) {
  
  end_offset_ = value;
}
inline void IncidentsTile_Location::set_end_offset(float value) {
  _internal_set_end_offset(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Location.end_offset)
}

// uint32 metadata_index = 4;
inline void IncidentsTile_Location::clear_metadata_index() {
  metadata_index_ = 0u;
}
inline uint32_t IncidentsTile_Location::_internal_metadata_index() const {
  return metadata_index_;
}
inline uint32_t IncidentsTile_Location::metadata_index() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Location.metadata_index)
  return _internal_metadata_index();
}
inline void IncidentsTile_Location::_internal_set_metadata_index(uint32_t value) {
  
  metadata_index_ = value;
}
inline void IncidentsTile_Location::set_metadata_index(uint32_t value) {
  _internal_set_metadata_index(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Location.metadata_index)
}

// -------------------------------------------------------------------

// IncidentsTile_Metadata_Congestion

// uint32 value = 1;
inline void IncidentsTile_Metadata_Congestion::clear_value() {
  value_ = 0u;
}
inline uint32_t IncidentsTile_Metadata_Congestion::_internal_value() const {
  return value_;
}
inline uint32_t IncidentsTile_Metadata_Congestion::value() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.Congestion.value)
  return _internal_value();
}
inline void IncidentsTile_Metadata_Congestion::_internal_set_value(uint32_t value) {
  
  value_ = value;
}
inline void IncidentsTile_Metadata_Congestion::set_value(uint32_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.Congestion.value)
}

// -------------------------------------------------------------------

// IncidentsTile_Metadata

// .valhalla.IncidentsTile.Metadata.Type type = 1;
inline void IncidentsTile_Metadata::clear_type() {
  type_ = 0;
}
inline ::valhalla::IncidentsTile_Metadata_Type IncidentsTile_Metadata::_internal_type() const {
  return static_cast< ::valhalla::IncidentsTile_Metadata_Type >(type_);
}
inline ::valhalla::IncidentsTile_Metadata_Type IncidentsTile_Metadata::type() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.type)
  return _internal_type();
}
inline void IncidentsTile_Metadata::_internal_set_type(::valhalla::IncidentsTile_Metadata_Type value) {
  
  type_ = value;
}
inline void IncidentsTile_Metadata::set_type(::valhalla::IncidentsTile_Metadata_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.type)
}

// repeated uint32 alertc_codes = 2;
inline int IncidentsTile_Metadata::_internal_alertc_codes_size() const {
  return alertc_codes_.size();
}
inline int IncidentsTile_Metadata::alertc_codes_size() const {
  return _internal_alertc_codes_size();
}
inline void IncidentsTile_Metadata::clear_alertc_codes() {
  alertc_codes_.Clear();
}
inline uint32_t IncidentsTile_Metadata::_internal_alertc_codes(int index) const {
  return alertc_codes_.Get(index);
}
inline uint32_t IncidentsTile_Metadata::alertc_codes(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.alertc_codes)
  return _internal_alertc_codes(index);
}
inline void IncidentsTile_Metadata::set_alertc_codes(int index, uint32_t value) {
  alertc_codes_.Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.alertc_codes)
}
inline void IncidentsTile_Metadata::_internal_add_alertc_codes(uint32_t value) {
  alertc_codes_.Add(value);
}
inline void IncidentsTile_Metadata::add_alertc_codes(uint32_t value) {
  _internal_add_alertc_codes(value);
  // @@protoc_insertion_point(field_add:valhalla.IncidentsTile.Metadata.alertc_codes)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
IncidentsTile_Metadata::_internal_alertc_codes() const {
  return alertc_codes_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
IncidentsTile_Metadata::alertc_codes() const {
  // @@protoc_insertion_point(field_list:valhalla.IncidentsTile.Metadata.alertc_codes)
  return _internal_alertc_codes();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
IncidentsTile_Metadata::_internal_mutable_alertc_codes() {
  return &alertc_codes_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
IncidentsTile_Metadata::mutable_alertc_codes() {
  // @@protoc_insertion_point(field_mutable_list:valhalla.IncidentsTile.Metadata.alertc_codes)
  return _internal_mutable_alertc_codes();
}

// string description = 3;
inline void IncidentsTile_Metadata::clear_description() {
  description_.ClearToEmpty();
}
inline const std::string& IncidentsTile_Metadata::description() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.description)
  return _internal_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IncidentsTile_Metadata::set_description(ArgT0&& arg0, ArgT... args) {
 
 description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.description)
}
inline std::string* IncidentsTile_Metadata::mutable_description() {
  std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:valhalla.IncidentsTile.Metadata.description)
  return _s;
}
inline const std::string& IncidentsTile_Metadata::_internal_description() const {
  return description_.Get();
}
inline void IncidentsTile_Metadata::_internal_set_description(const std::string& value) {
  
  description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::_internal_mutable_description() {
  
  return description_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::release_description() {
  // @@protoc_insertion_point(field_release:valhalla.IncidentsTile.Metadata.description)
  return description_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IncidentsTile_Metadata::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  description_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (description_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:valhalla.IncidentsTile.Metadata.description)
}

// string sub_type = 4;
inline void IncidentsTile_Metadata::clear_sub_type() {
  sub_type_.ClearToEmpty();
}
inline const std::string& IncidentsTile_Metadata::sub_type() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.sub_type)
  return _internal_sub_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IncidentsTile_Metadata::set_sub_type(ArgT0&& arg0, ArgT... args) {
 
 sub_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.sub_type)
}
inline std::string* IncidentsTile_Metadata::mutable_sub_type() {
  std::string* _s = _internal_mutable_sub_type();
  // @@protoc_insertion_point(field_mutable:valhalla.IncidentsTile.Metadata.sub_type)
  return _s;
}
inline const std::string& IncidentsTile_Metadata::_internal_sub_type() const {
  return sub_type_.Get();
}
inline void IncidentsTile_Metadata::_internal_set_sub_type(const std::string& value) {
  
  sub_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::_internal_mutable_sub_type() {
  
  return sub_type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::release_sub_type() {
  // @@protoc_insertion_point(field_release:valhalla.IncidentsTile.Metadata.sub_type)
  return sub_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IncidentsTile_Metadata::set_allocated_sub_type(std::string* sub_type) {
  if (sub_type != nullptr) {
    
  } else {
    
  }
  sub_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sub_type,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sub_type_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    sub_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:valhalla.IncidentsTile.Metadata.sub_type)
}

// string sub_type_description = 5;
inline void IncidentsTile_Metadata::clear_sub_type_description() {
  sub_type_description_.ClearToEmpty();
}
inline const std::string& IncidentsTile_Metadata::sub_type_description() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.sub_type_description)
  return _internal_sub_type_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IncidentsTile_Metadata::set_sub_type_description(ArgT0&& arg0, ArgT... args) {
 
 sub_type_description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.sub_type_description)
}
inline std::string* IncidentsTile_Metadata::mutable_sub_type_description() {
  std::string* _s = _internal_mutable_sub_type_description();
  // @@protoc_insertion_point(field_mutable:valhalla.IncidentsTile.Metadata.sub_type_description)
  return _s;
}
inline const std::string& IncidentsTile_Metadata::_internal_sub_type_description() const {
  return sub_type_description_.Get();
}
inline void IncidentsTile_Metadata::_internal_set_sub_type_description(const std::string& value) {
  
  sub_type_description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::_internal_mutable_sub_type_description() {
  
  return sub_type_description_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::release_sub_type_description() {
  // @@protoc_insertion_point(field_release:valhalla.IncidentsTile.Metadata.sub_type_description)
  return sub_type_description_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IncidentsTile_Metadata::set_allocated_sub_type_description(std::string* sub_type_description) {
  if (sub_type_description != nullptr) {
    
  } else {
    
  }
  sub_type_description_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sub_type_description,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sub_type_description_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    sub_type_description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:valhalla.IncidentsTile.Metadata.sub_type_description)
}

// uint64 start_time = 6;
inline void IncidentsTile_Metadata::clear_start_time() {
  start_time_ = uint64_t{0u};
}
inline uint64_t IncidentsTile_Metadata::_internal_start_time() const {
  return start_time_;
}
inline uint64_t IncidentsTile_Metadata::start_time() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.start_time)
  return _internal_start_time();
}
inline void IncidentsTile_Metadata::_internal_set_start_time(uint64_t value) {
  
  start_time_ = value;
}
inline void IncidentsTile_Metadata::set_start_time(uint64_t value) {
  _internal_set_start_time(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.start_time)
}

// uint64 end_time = 7;
inline void IncidentsTile_Metadata::clear_end_time() {
  end_time_ = uint64_t{0u};
}
inline uint64_t IncidentsTile_Metadata::_internal_end_time() const {
  return end_time_;
}
inline uint64_t IncidentsTile_Metadata::end_time() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.end_time)
  return _internal_end_time();
}
inline void IncidentsTile_Metadata::_internal_set_end_time(uint64_t value) {
  
  end_time_ = value;
}
inline void IncidentsTile_Metadata::set_end_time(uint64_t value) {
  _internal_set_end_time(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.end_time)
}

// .valhalla.IncidentsTile.Metadata.Impact impact = 9;
inline void IncidentsTile_Metadata::clear_impact() {
  impact_ = 0;
}
inline ::valhalla::IncidentsTile_Metadata_Impact IncidentsTile_Metadata::_internal_impact() const {
  return static_cast< ::valhalla::IncidentsTile_Metadata_Impact >(impact_);
}
inline ::valhalla::IncidentsTile_Metadata_Impact IncidentsTile_Metadata::impact() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.impact)
  return _internal_impact();
}
inline void IncidentsTile_Metadata::_internal_set_impact(::valhalla::IncidentsTile_Metadata_Impact value) {
  
  impact_ = value;
}
inline void IncidentsTile_Metadata::set_impact(::valhalla::IncidentsTile_Metadata_Impact value) {
  _internal_set_impact(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.impact)
}

// bool road_closed = 10;
inline void IncidentsTile_Metadata::clear_road_closed() {
  road_closed_ = false;
}
inline bool IncidentsTile_Metadata::_internal_road_closed() const {
  return road_closed_;
}
inline bool IncidentsTile_Metadata::road_closed() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.road_closed)
  return _internal_road_closed();
}
inline void IncidentsTile_Metadata::_internal_set_road_closed(bool value) {
  
  road_closed_ = value;
}
inline void IncidentsTile_Metadata::set_road_closed(bool value) {
  _internal_set_road_closed(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.road_closed)
}

// .valhalla.IncidentsTile.Metadata.Congestion congestion = 11;
inline bool IncidentsTile_Metadata::_internal_has_congestion() const {
  return this != internal_default_instance() && congestion_ != nullptr;
}
inline bool IncidentsTile_Metadata::has_congestion() const {
  return _internal_has_congestion();
}
inline void IncidentsTile_Metadata::clear_congestion() {
  if (GetArenaForAllocation() == nullptr && congestion_ != nullptr) {
    delete congestion_;
  }
  congestion_ = nullptr;
}
inline const ::valhalla::IncidentsTile_Metadata_Congestion& IncidentsTile_Metadata::_internal_congestion() const {
  const ::valhalla::IncidentsTile_Metadata_Congestion* p = congestion_;
  return p != nullptr ? *p : reinterpret_cast<const ::valhalla::IncidentsTile_Metadata_Congestion&>(
      ::valhalla::_IncidentsTile_Metadata_Congestion_default_instance_);
}
inline const ::valhalla::IncidentsTile_Metadata_Congestion& IncidentsTile_Metadata::congestion() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.congestion)
  return _internal_congestion();
}
inline void IncidentsTile_Metadata::unsafe_arena_set_allocated_congestion(
    ::valhalla::IncidentsTile_Metadata_Congestion* congestion) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(congestion_);
  }
  congestion_ = congestion;
  if (congestion) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:valhalla.IncidentsTile.Metadata.congestion)
}
inline ::valhalla::IncidentsTile_Metadata_Congestion* IncidentsTile_Metadata::release_congestion() {
  
  ::valhalla::IncidentsTile_Metadata_Congestion* temp = congestion_;
  congestion_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::valhalla::IncidentsTile_Metadata_Congestion* IncidentsTile_Metadata::unsafe_arena_release_congestion() {
  // @@protoc_insertion_point(field_release:valhalla.IncidentsTile.Metadata.congestion)
  
  ::valhalla::IncidentsTile_Metadata_Congestion* temp = congestion_;
  congestion_ = nullptr;
  return temp;
}
inline ::valhalla::IncidentsTile_Metadata_Congestion* IncidentsTile_Metadata::_internal_mutable_congestion() {
  
  if (congestion_ == nullptr) {
    auto* p = CreateMaybeMessage<::valhalla::IncidentsTile_Metadata_Congestion>(GetArenaForAllocation());
    congestion_ = p;
  }
  return congestion_;
}
inline ::valhalla::IncidentsTile_Metadata_Congestion* IncidentsTile_Metadata::mutable_congestion() {
  ::valhalla::IncidentsTile_Metadata_Congestion* _msg = _internal_mutable_congestion();
  // @@protoc_insertion_point(field_mutable:valhalla.IncidentsTile.Metadata.congestion)
  return _msg;
}
inline void IncidentsTile_Metadata::set_allocated_congestion(::valhalla::IncidentsTile_Metadata_Congestion* congestion) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete congestion_;
  }
  if (congestion) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::valhalla::IncidentsTile_Metadata_Congestion>::GetOwningArena(congestion);
    if (message_arena != submessage_arena) {
      congestion = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, congestion, submessage_arena);
    }
    
  } else {
    
  }
  congestion_ = congestion;
  // @@protoc_insertion_point(field_set_allocated:valhalla.IncidentsTile.Metadata.congestion)
}

// repeated string lanes_blocked = 12;
inline int IncidentsTile_Metadata::_internal_lanes_blocked_size() const {
  return lanes_blocked_.size();
}
inline int IncidentsTile_Metadata::lanes_blocked_size() const {
  return _internal_lanes_blocked_size();
}
inline void IncidentsTile_Metadata::clear_lanes_blocked() {
  lanes_blocked_.Clear();
}
inline std::string* IncidentsTile_Metadata::add_lanes_blocked() {
  std::string* _s = _internal_add_lanes_blocked();
  // @@protoc_insertion_point(field_add_mutable:valhalla.IncidentsTile.Metadata.lanes_blocked)
  return _s;
}
inline const std::string& IncidentsTile_Metadata::_internal_lanes_blocked(int index) const {
  return lanes_blocked_.Get(index);
}
inline const std::string& IncidentsTile_Metadata::lanes_blocked(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.lanes_blocked)
  return _internal_lanes_blocked(index);
}
inline std::string* IncidentsTile_Metadata::mutable_lanes_blocked(int index) {
  // @@protoc_insertion_point(field_mutable:valhalla.IncidentsTile.Metadata.lanes_blocked)
  return lanes_blocked_.Mutable(index);
}
inline void IncidentsTile_Metadata::set_lanes_blocked(int index, const std::string& value) {
  lanes_blocked_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.lanes_blocked)
}
inline void IncidentsTile_Metadata::set_lanes_blocked(int index, std::string&& value) {
  lanes_blocked_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.lanes_blocked)
}
inline void IncidentsTile_Metadata::set_lanes_blocked(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  lanes_blocked_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:valhalla.IncidentsTile.Metadata.lanes_blocked)
}
inline void IncidentsTile_Metadata::set_lanes_blocked(int index, const char* value, size_t size) {
  lanes_blocked_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:valhalla.IncidentsTile.Metadata.lanes_blocked)
}
inline std::string* IncidentsTile_Metadata::_internal_add_lanes_blocked() {
  return lanes_blocked_.Add();
}
inline void IncidentsTile_Metadata::add_lanes_blocked(const std::string& value) {
  lanes_blocked_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:valhalla.IncidentsTile.Metadata.lanes_blocked)
}
inline void IncidentsTile_Metadata::add_lanes_blocked(std::string&& value) {
  lanes_blocked_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:valhalla.IncidentsTile.Metadata.lanes_blocked)
}
inline void IncidentsTile_Metadata::add_lanes_blocked(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  lanes_blocked_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:valhalla.IncidentsTile.Metadata.lanes_blocked)
}
inline void IncidentsTile_Metadata::add_lanes_blocked(const char* value, size_t size) {
  lanes_blocked_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:valhalla.IncidentsTile.Metadata.lanes_blocked)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
IncidentsTile_Metadata::lanes_blocked() const {
  // @@protoc_insertion_point(field_list:valhalla.IncidentsTile.Metadata.lanes_blocked)
  return lanes_blocked_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
IncidentsTile_Metadata::mutable_lanes_blocked() {
  // @@protoc_insertion_point(field_mutable_list:valhalla.IncidentsTile.Metadata.lanes_blocked)
  return &lanes_blocked_;
}

// uint64 creation_time = 13;
inline void IncidentsTile_Metadata::clear_creation_time() {
  creation_time_ = uint64_t{0u};
}
inline uint64_t IncidentsTile_Metadata::_internal_creation_time() const {
  return creation_time_;
}
inline uint64_t IncidentsTile_Metadata::creation_time() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.creation_time)
  return _internal_creation_time();
}
inline void IncidentsTile_Metadata::_internal_set_creation_time(uint64_t value) {
  
  creation_time_ = value;
}
inline void IncidentsTile_Metadata::set_creation_time(uint64_t value) {
  _internal_set_creation_time(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.creation_time)
}

// string long_description = 14;
inline void IncidentsTile_Metadata::clear_long_description() {
  long_description_.ClearToEmpty();
}
inline const std::string& IncidentsTile_Metadata::long_description() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.long_description)
  return _internal_long_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IncidentsTile_Metadata::set_long_description(ArgT0&& arg0, ArgT... args) {
 
 long_description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.long_description)
}
inline std::string* IncidentsTile_Metadata::mutable_long_description() {
  std::string* _s = _internal_mutable_long_description();
  // @@protoc_insertion_point(field_mutable:valhalla.IncidentsTile.Metadata.long_description)
  return _s;
}
inline const std::string& IncidentsTile_Metadata::_internal_long_description() const {
  return long_description_.Get();
}
inline void IncidentsTile_Metadata::_internal_set_long_description(const std::string& value) {
  
  long_description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::_internal_mutable_long_description() {
  
  return long_description_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::release_long_description() {
  // @@protoc_insertion_point(field_release:valhalla.IncidentsTile.Metadata.long_description)
  return long_description_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IncidentsTile_Metadata::set_allocated_long_description(std::string* long_description) {
  if (long_description != nullptr) {
    
  } else {
    
  }
  long_description_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), long_description,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (long_description_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    long_description_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:valhalla.IncidentsTile.Metadata.long_description)
}

// string clear_lanes = 15;
inline void IncidentsTile_Metadata::clear_clear_lanes() {
  clear_lanes_.ClearToEmpty();
}
inline const std::string& IncidentsTile_Metadata::clear_lanes() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.clear_lanes)
  return _internal_clear_lanes();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IncidentsTile_Metadata::set_clear_lanes(ArgT0&& arg0, ArgT... args) {
 
 clear_lanes_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.clear_lanes)
}
inline std::string* IncidentsTile_Metadata::mutable_clear_lanes() {
  std::string* _s = _internal_mutable_clear_lanes();
  // @@protoc_insertion_point(field_mutable:valhalla.IncidentsTile.Metadata.clear_lanes)
  return _s;
}
inline const std::string& IncidentsTile_Metadata::_internal_clear_lanes() const {
  return clear_lanes_.Get();
}
inline void IncidentsTile_Metadata::_internal_set_clear_lanes(const std::string& value) {
  
  clear_lanes_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::_internal_mutable_clear_lanes() {
  
  return clear_lanes_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::release_clear_lanes() {
  // @@protoc_insertion_point(field_release:valhalla.IncidentsTile.Metadata.clear_lanes)
  return clear_lanes_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IncidentsTile_Metadata::set_allocated_clear_lanes(std::string* clear_lanes) {
  if (clear_lanes != nullptr) {
    
  } else {
    
  }
  clear_lanes_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), clear_lanes,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (clear_lanes_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    clear_lanes_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:valhalla.IncidentsTile.Metadata.clear_lanes)
}

// uint64 num_lanes_blocked = 16;
inline void IncidentsTile_Metadata::clear_num_lanes_blocked() {
  num_lanes_blocked_ = uint64_t{0u};
}
inline uint64_t IncidentsTile_Metadata::_internal_num_lanes_blocked() const {
  return num_lanes_blocked_;
}
inline uint64_t IncidentsTile_Metadata::num_lanes_blocked() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.num_lanes_blocked)
  return _internal_num_lanes_blocked();
}
inline void IncidentsTile_Metadata::_internal_set_num_lanes_blocked(uint64_t value) {
  
  num_lanes_blocked_ = value;
}
inline void IncidentsTile_Metadata::set_num_lanes_blocked(uint64_t value) {
  _internal_set_num_lanes_blocked(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.num_lanes_blocked)
}

// uint32 length = 17;
inline void IncidentsTile_Metadata::clear_length() {
  length_ = 0u;
}
inline uint32_t IncidentsTile_Metadata::_internal_length() const {
  return length_;
}
inline uint32_t IncidentsTile_Metadata::length() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.length)
  return _internal_length();
}
inline void IncidentsTile_Metadata::_internal_set_length(uint32_t value) {
  
  length_ = value;
}
inline void IncidentsTile_Metadata::set_length(uint32_t value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.length)
}

// uint64 id = 128;
inline void IncidentsTile_Metadata::clear_id() {
  id_ = uint64_t{0u};
}
inline uint64_t IncidentsTile_Metadata::_internal_id() const {
  return id_;
}
inline uint64_t IncidentsTile_Metadata::id() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.id)
  return _internal_id();
}
inline void IncidentsTile_Metadata::_internal_set_id(uint64_t value) {
  
  id_ = value;
}
inline void IncidentsTile_Metadata::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.id)
}

// string iso_3166_1_alpha2 = 129;
inline void IncidentsTile_Metadata::clear_iso_3166_1_alpha2() {
  iso_3166_1_alpha2_.ClearToEmpty();
}
inline const std::string& IncidentsTile_Metadata::iso_3166_1_alpha2() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.iso_3166_1_alpha2)
  return _internal_iso_3166_1_alpha2();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IncidentsTile_Metadata::set_iso_3166_1_alpha2(ArgT0&& arg0, ArgT... args) {
 
 iso_3166_1_alpha2_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.iso_3166_1_alpha2)
}
inline std::string* IncidentsTile_Metadata::mutable_iso_3166_1_alpha2() {
  std::string* _s = _internal_mutable_iso_3166_1_alpha2();
  // @@protoc_insertion_point(field_mutable:valhalla.IncidentsTile.Metadata.iso_3166_1_alpha2)
  return _s;
}
inline const std::string& IncidentsTile_Metadata::_internal_iso_3166_1_alpha2() const {
  return iso_3166_1_alpha2_.Get();
}
inline void IncidentsTile_Metadata::_internal_set_iso_3166_1_alpha2(const std::string& value) {
  
  iso_3166_1_alpha2_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::_internal_mutable_iso_3166_1_alpha2() {
  
  return iso_3166_1_alpha2_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::release_iso_3166_1_alpha2() {
  // @@protoc_insertion_point(field_release:valhalla.IncidentsTile.Metadata.iso_3166_1_alpha2)
  return iso_3166_1_alpha2_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IncidentsTile_Metadata::set_allocated_iso_3166_1_alpha2(std::string* iso_3166_1_alpha2) {
  if (iso_3166_1_alpha2 != nullptr) {
    
  } else {
    
  }
  iso_3166_1_alpha2_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), iso_3166_1_alpha2,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (iso_3166_1_alpha2_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    iso_3166_1_alpha2_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:valhalla.IncidentsTile.Metadata.iso_3166_1_alpha2)
}

// string iso_3166_1_alpha3 = 130;
inline void IncidentsTile_Metadata::clear_iso_3166_1_alpha3() {
  iso_3166_1_alpha3_.ClearToEmpty();
}
inline const std::string& IncidentsTile_Metadata::iso_3166_1_alpha3() const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.Metadata.iso_3166_1_alpha3)
  return _internal_iso_3166_1_alpha3();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IncidentsTile_Metadata::set_iso_3166_1_alpha3(ArgT0&& arg0, ArgT... args) {
 
 iso_3166_1_alpha3_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:valhalla.IncidentsTile.Metadata.iso_3166_1_alpha3)
}
inline std::string* IncidentsTile_Metadata::mutable_iso_3166_1_alpha3() {
  std::string* _s = _internal_mutable_iso_3166_1_alpha3();
  // @@protoc_insertion_point(field_mutable:valhalla.IncidentsTile.Metadata.iso_3166_1_alpha3)
  return _s;
}
inline const std::string& IncidentsTile_Metadata::_internal_iso_3166_1_alpha3() const {
  return iso_3166_1_alpha3_.Get();
}
inline void IncidentsTile_Metadata::_internal_set_iso_3166_1_alpha3(const std::string& value) {
  
  iso_3166_1_alpha3_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::_internal_mutable_iso_3166_1_alpha3() {
  
  return iso_3166_1_alpha3_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* IncidentsTile_Metadata::release_iso_3166_1_alpha3() {
  // @@protoc_insertion_point(field_release:valhalla.IncidentsTile.Metadata.iso_3166_1_alpha3)
  return iso_3166_1_alpha3_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void IncidentsTile_Metadata::set_allocated_iso_3166_1_alpha3(std::string* iso_3166_1_alpha3) {
  if (iso_3166_1_alpha3 != nullptr) {
    
  } else {
    
  }
  iso_3166_1_alpha3_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), iso_3166_1_alpha3,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (iso_3166_1_alpha3_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    iso_3166_1_alpha3_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:valhalla.IncidentsTile.Metadata.iso_3166_1_alpha3)
}

// -------------------------------------------------------------------

// IncidentsTile

// repeated .valhalla.IncidentsTile.Location locations = 1;
inline int IncidentsTile::_internal_locations_size() const {
  return locations_.size();
}
inline int IncidentsTile::locations_size() const {
  return _internal_locations_size();
}
inline void IncidentsTile::clear_locations() {
  locations_.Clear();
}
inline ::valhalla::IncidentsTile_Location* IncidentsTile::mutable_locations(int index) {
  // @@protoc_insertion_point(field_mutable:valhalla.IncidentsTile.locations)
  return locations_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::valhalla::IncidentsTile_Location >*
IncidentsTile::mutable_locations() {
  // @@protoc_insertion_point(field_mutable_list:valhalla.IncidentsTile.locations)
  return &locations_;
}
inline const ::valhalla::IncidentsTile_Location& IncidentsTile::_internal_locations(int index) const {
  return locations_.Get(index);
}
inline const ::valhalla::IncidentsTile_Location& IncidentsTile::locations(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.locations)
  return _internal_locations(index);
}
inline ::valhalla::IncidentsTile_Location* IncidentsTile::_internal_add_locations() {
  return locations_.Add();
}
inline ::valhalla::IncidentsTile_Location* IncidentsTile::add_locations() {
  ::valhalla::IncidentsTile_Location* _add = _internal_add_locations();
  // @@protoc_insertion_point(field_add:valhalla.IncidentsTile.locations)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::valhalla::IncidentsTile_Location >&
IncidentsTile::locations() const {
  // @@protoc_insertion_point(field_list:valhalla.IncidentsTile.locations)
  return locations_;
}

// repeated .valhalla.IncidentsTile.Metadata metadata = 2;
inline int IncidentsTile::_internal_metadata_size() const {
  return metadata_.size();
}
inline int IncidentsTile::metadata_size() const {
  return _internal_metadata_size();
}
inline void IncidentsTile::clear_metadata() {
  metadata_.Clear();
}
inline ::valhalla::IncidentsTile_Metadata* IncidentsTile::mutable_metadata(int index) {
  // @@protoc_insertion_point(field_mutable:valhalla.IncidentsTile.metadata)
  return metadata_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::valhalla::IncidentsTile_Metadata >*
IncidentsTile::mutable_metadata() {
  // @@protoc_insertion_point(field_mutable_list:valhalla.IncidentsTile.metadata)
  return &metadata_;
}
inline const ::valhalla::IncidentsTile_Metadata& IncidentsTile::_internal_metadata(int index) const {
  return metadata_.Get(index);
}
inline const ::valhalla::IncidentsTile_Metadata& IncidentsTile::metadata(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.IncidentsTile.metadata)
  return _internal_metadata(index);
}
inline ::valhalla::IncidentsTile_Metadata* IncidentsTile::_internal_add_metadata() {
  return metadata_.Add();
}
inline ::valhalla::IncidentsTile_Metadata* IncidentsTile::add_metadata() {
  ::valhalla::IncidentsTile_Metadata* _add = _internal_add_metadata();
  // @@protoc_insertion_point(field_add:valhalla.IncidentsTile.metadata)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::valhalla::IncidentsTile_Metadata >&
IncidentsTile::metadata() const {
  // @@protoc_insertion_point(field_list:valhalla.IncidentsTile.metadata)
  return metadata_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace valhalla

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::valhalla::IncidentsTile_Metadata_Type> : ::std::true_type {};
template <> struct is_proto_enum< ::valhalla::IncidentsTile_Metadata_Impact> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_incidents_2eproto
