#!/bin/bash
set -e

function usage() {
	echo "Usage: $0 config_file data_file(s)
	exit 1
}

config=$1
datafiles=$2

# Initialize (e.g. create the directory or remove files if it already exists)
valhalla_build_tiles --config $1 --start initialize --end initialize $datafiles
if [ "$?" != "0" ]; then
    echo "[Error] tile initialization failed!" 1>&2
    exit 1
fi

# Parse OSM PBF
valhalla_build_tiles --config $1 --start parse --end parse $datafiles
if [ "$?" != "0" ]; then
    echo "[Error] OSM PBF parsing failed!" 1>&2
    exit 1
fi

# Build tiles
valhalla_build_tiles --config $1 --start build --end build $datafiles
if [ "$?" != "0" ]; then
    echo "[Error] build tiles failed!" 1>&2
    exit 1
fi

# Enhance tiles
valhalla_build_tiles --config $1 --start enhance --end enhance $datafiles
if [ "$?" != "0" ]; then
    echo "[Error] Enhance tiles failed!" 1>&2
    exit 1
fi

# Filter tiles (optional - based on config)
valhalla_build_tiles --config $1 --start filter --end filter $datafiles
if [ "$?" != "0" ]; then
    echo "[Error] Filter tiles failed!" 1>&2
    exit 1
fi

# Add transit tiles (optional - based on config)
valhalla_build_tiles --config $1 --start transit --end transit $datafiles
if [ "$?" != "0" ]; then
    echo "[Error] Add transit tiles failed!" 1>&2
    exit 1
fi

# Create hierarchy (optional - based on config)
valhalla_build_tiles --config $1 --start hierarchy --end hierarchy $datafiles
if [ "$?" != "0" ]; then
    echo "[Error] Hierarchy building failed!" 1>&2
    exit 1
fi

# Create shortcuts (optional - based on config)
valhalla_build_tiles --config $1 --start shortcuts --end shortcuts $datafiles
if [ "$?" != "0" ]; then
    echo "[Error] Shortcut building failed!" 1>&2
    exit 1
fi

# Add restrictions
valhalla_build_tiles --config $1 --start restrictions --end restrictions $datafiles
if [ "$?" != "0" ]; then
    echo "[Error] Adding complex restrictions failed!" 1>&2
    exit 1
fi

# Validate data
valhalla_build_tiles --config $1 --start validate --end validate $datafiles
if [ "$?" != "0" ]; then
    echo "[Error] Validate tiles failed!" 1>&2
    exit 1
fi

# Cleanup temporary files
valhalla_build_tiles --config $1 --start cleanup --end cleanup $datafiles
if [ "$?" != "0" ]; then
    echo "[Error] Cleanup temporary data failed!" 1>&2
    exit 1
fi
