# AUTO-GENERATED by nanobind_add_stub from the matching C++ binding.
# Do not edit by hand — your changes will be overwritten on the next build.
# See src/bindings/python/README.md ("Type stubs") for the regeneration workflow.

VALHALLA_PRINT_VERSION: str = '3.7.0'

class ValhallaError(RuntimeError):
    """
    Exception raised when a Valhalla operation fails.

    :param int code: Valhalla-internal error code.
    :param str message: Human-readable error message.
    :param int http_code: Corresponding HTTP status code.
    :param str http_message: Corresponding HTTP status message.
    """

class _Actor:
    def __init__(self, config: str) -> None: ...

    def route(self, arg: str, /) -> str: ...

    def locate(self, arg: str, /) -> str: ...

    def optimized_route(self, arg: str, /) -> str:
        """Optimizes the order of a set of waypoints by time."""

    def matrix(self, arg: str, /) -> str: ...

    def isochrone(self, arg: str, /) -> str: ...

    def trace_route(self, arg: str, /) -> str: ...

    def trace_attributes(self, arg: str, /) -> str: ...

    def height(self, arg: str, /) -> str: ...

    def transit_available(self, arg: str, /) -> str: ...

    def expansion(self, arg: str, /) -> str: ...

    def centroid(self, arg: str, /) -> str: ...

    def status(self, arg: str, /) -> str: ...

    def tile(self, arg: str, /) -> bytes: ...
