#!/usr/bin/env python3
"""Dev-only generator for translit.py. Never imported by the scoring path.

    python3 scripts/geocoding_demo/gen_translit.py           # rewrite translit.py
    python3 scripts/geocoding_demo/gen_translit.py --check    # verify it is up to date

Three sources feed the table, in order of precedence:

1. NFKD decomposition with combining marks dropped, kept when the result is pure ASCII. Handles the
   261 ordinary accented letters (a-umlaut, e-acute, c-caron, ...).
2. The Unicode character name, for `LATIN {CAPITAL|SMALL} LETTER <X> WITH <modifier>` - the base
   letter is in the name. Handles 70 stroke/hook/topbar/bar/curl letters NFKD leaves alone.
3. EXCEPTIONS below, for the rest: ligatures, eth/thorn/sharp-s, and the phonetic letters whose
   names carry no base letter.

Valhalla has no ICU and header-only Boost cannot normalize, so the C++ side needs this as a literal
table regardless. NFKD alone would not do anyway - sharp-s, slashed-o, stroked-l and the ae/oe
ligatures are not decomposable, so transliteration has to be a deliberate choice per codepoint.
"""

import argparse
import os
import re
import sys
import unicodedata

RANGE_START = 0x00A0  # Latin-1 Supplement
RANGE_END = 0x0250  # end of Latin Extended-B, exclusive

# base letter is not recoverable from NFKD or from the character name
EXCEPTIONS = {
    # relevant to European street names
    0x00B5: "u",  # micro sign
    0x00C6: "ae",
    0x00E6: "ae",
    0x00D0: "d",  # eth
    0x00F0: "d",
    0x00DE: "th",  # thorn
    0x00FE: "th",
    0x00DF: "ss",  # sharp s
    0x0131: "i",  # dotless i, Turkish
    0x0138: "k",  # kra, Greenlandic
    0x0149: "n",
    0x014A: "ng",  # eng, Sami
    0x014B: "ng",
    0x0152: "oe",
    0x0153: "oe",
    0x01E2: "ae",
    0x01E3: "ae",
    0x01FC: "ae",
    0x01FD: "ae",
    0x0195: "hv",
    0x01F6: "hv",  # hwair
    0x01BF: "w",  # wynn
    0x01F7: "w",
    0x021C: "gh",  # yogh
    0x021D: "gh",
    0x0222: "ou",
    0x0223: "ou",
    0x0237: "j",  # dotless j
    0x0244: "u",
    0x024A: "q",
    # phonetic letters, folded to the nearest base for completeness
    0x0186: "o",
    0x0189: "d",
    0x018D: "d",
    0x018E: "e",
    0x018F: "e",  # schwa
    0x0190: "e",
    0x01DD: "e",
    0x0194: "g",
    0x0196: "i",
    0x019B: "l",
    0x019C: "m",
    0x01A2: "oi",
    0x01A3: "oi",
    0x01A6: "r",
    0x01A9: "s",  # esh
    0x01AA: "s",
    0x01B1: "u",
    0x01B7: "z",  # ezh
    0x01B8: "z",
    0x01B9: "z",
    0x01BA: "z",
    0x01EE: "z",
    0x01EF: "z",
    0x0238: "db",
    0x0239: "qp",
    0x0245: "v",
}

# tone letters, clicks and glottal stops: no sensible ASCII form and never in a street name, so they
# stay out of the table and pass through unchanged at runtime, like any other unmapped script
DELIBERATELY_UNMAPPED = frozenset(
    [
        0x0184,
        0x0185,
        0x01A7,
        0x01A8,
        0x01BB,
        0x01BC,
        0x01BD,
        0x01BE,
        0x01C0,
        0x01C1,
        0x01C2,
        0x01C3,
        0x0241,
        0x0242,
    ]
)

NAME_RE = re.compile(r"^LATIN (?:CAPITAL|SMALL) LETTER ([A-Z])(?: WITH .*)?$")
OUTPUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "translit.py")


def _nfkd_ascii(codepoint):
    decomposed = unicodedata.normalize("NFKD", chr(codepoint))
    stripped = "".join(c for c in decomposed if not unicodedata.combining(c))
    if stripped and all(ord(c) < 128 for c in stripped):
        return stripped.lower()
    return None


def _from_name(codepoint):
    match = NAME_RE.match(unicodedata.name(chr(codepoint), ""))
    return match.group(1).lower() if match else None


def build():
    """Return (table, unmapped) where table maps codepoint -> lowercase ASCII."""
    table = {}
    unmapped = []
    for codepoint in range(RANGE_START, RANGE_END):
        char = chr(codepoint)
        if not unicodedata.category(char).startswith("L"):
            continue
        folded = EXCEPTIONS.get(codepoint) or _nfkd_ascii(codepoint) or _from_name(codepoint)
        if folded is None:
            unmapped.append(codepoint)
        else:
            table[codepoint] = folded
    return table, unmapped


def render(table):
    lines = [
        '"""Codepoint -> lowercase ASCII fold table. GENERATED by gen_translit.py, do not edit.',
        "",
        "Data only, no imports: this is the file that becomes a constexpr array in C++.",
        '"""',
        "",
        "FOLD = {",
    ]
    for codepoint in sorted(table):
        lines.append(
            '    0x{:04x}: "{}",  # {} {}'.format(
                codepoint,
                table[codepoint],
                chr(codepoint),
                unicodedata.name(chr(codepoint), "?"),
            )
        )
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv):
    parser = argparse.ArgumentParser(description="generate translit.py")
    parser.add_argument("--check", action="store_true", help="verify translit.py is up to date")
    args = parser.parse_args(argv)

    table, unmapped = build()
    rendered = render(table)

    unexpected = [c for c in unmapped if c not in DELIBERATELY_UNMAPPED]
    print("unicode {} on python {}".format(unicodedata.unidata_version, sys.version.split()[0]))
    print(
        "U+{:04X}..U+{:04X}: {} letters, {} mapped, {} unmapped ({} deliberately)".format(
            RANGE_START,
            RANGE_END - 1,
            len(table) + len(unmapped),
            len(table),
            len(unmapped),
            len(unmapped) - len(unexpected),
        )
    )
    for codepoint in unexpected:
        print(
            "  unexpected unmapped: U+{:04X} {} {}".format(
                codepoint, chr(codepoint), unicodedata.name(chr(codepoint), "?")
            )
        )

    if args.check:
        current = open(OUTPUT, encoding="utf-8").read() if os.path.exists(OUTPUT) else ""
        if current != rendered:
            print("\ntranslit.py is stale - rerun without --check", file=sys.stderr)
            return 1
        print("\ntranslit.py is up to date")
        return 1 if unexpected else 0

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write(rendered)
    print("\nwrote {} entries to {}".format(len(table), OUTPUT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
