on:
  pull_request:
    branches: 
      - master
    types:
      - closed

jobs:
  clear_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Install and setup mc client
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          mc --help
          mc alias set hetzner https://hel1.your-objectstorage.com {{ secrets.HETZNER_S3_ACCESS_KEY }} ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
      
      - name: Remove matching cache objects
        run: |
          # filter objects to ones matching this branch
          all_objects=$(mc ls --quiet gha-cache/gha-cache | awk '{ print $6 }')
          filtered=()
          # -n $line: if there's no \newline at the end, read will miss the last line
          echo $all_objects | while read -r line || [ -n "$line" ]; do
            if [[ "$line" == *"${{ github.head_ref }}" ]]; then
              filtered+=($line)
            fi
          done

          for entry in $filtered; do
            mc rm gha-cache/gha-cache/${entry} || echo "couldn't find $entry"
          done
