name: osx

on:
  push:
    paths-ignore:
      - "**.md"
      - .circleci/
      - docs/
      - run_route_scripts/
      - test_requests/
      - test/check_compilers/
      - .github/workflows/check_compilers.yml
      - ".tx"
      - ".git*"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "*.md"
      - .circleci/
      - docs/
      - run_route_scripts/
      - test_requests/
      - test/check_compilers/
      - .github/workflows/check_compilers.yml
      - ".tx"
      - ".git*"
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SETUP_TMATE: ${{ ((github.event_name == 'workflow_dispatch') && (github.event.inputs.debug_enabled == 'true')) && (github.repository_owner == 'valhalla') }}

jobs:
  lint:
    uses: ./.github/workflows/format.yml

  build_osx:
    # arm64 image; lowest available version for broad compatibility
    runs-on: macos-14
    name: release
    needs: [lint]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-tags: true

      - name: Install dependencies
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install python autoconf automake protobuf cmake ccache libtool sqlite3 libspatialite luajit curl wget czmq lz4 spatialite-tools unzip boost gdal libtiff libgeotiff
          export PATH="$(brew --prefix python)/libexec/bin:$PATH"
          python -m pip install --break-system-packages requests shapely numpy polib
          git clone --branch=0.12.0 --recurse-submodules https://github.com/kevinkreiser/prime_server && cd prime_server && cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_WERROR=OFF && cmake --build build -j$(sysctl -n hw.logicalcpu) && sudo cmake --install build

      - name: Get branch name
        run: echo "VALHALLA_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - name: Restore ccache
        uses: tespkg/actions-cache/restore@v1
        id: cache-ccache-restore
        with:
          endpoint: fsn1.your-objectstorage.com
          accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
          secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
          bucket: gha-cache-2
          key: ccache-osx-${{ env.VALHALLA_BRANCH }}
          restore-keys: |
            ccache-osx-master
            ccache-osx-
          path: ~/Library/Caches/ccache

      - name: Configure CMake
        run: |
          export PATH="$(brew --prefix python)/libexec/bin:$PATH"
          cmake -B build -DENABLE_SINGLE_FILES_WERROR=OFF

      - name: Build & install Valhalla
        run: make -C build -j$(sysctl -n hw.logicalcpu) && sudo make -C build install

      - name: Build Tests
        run: make -C build -j$(sysctl -n hw.logicalcpu) tests

      - name: Delete cache to save the latest
        run: |
          KEY="${{ steps.cache-ccache-restore.outputs.cache-primary-key }}"
          gh cache delete ${KEY} || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save ccache
        uses: tespkg/actions-cache/save@v1
        with:
          endpoint: fsn1.your-objectstorage.com
          accessKey: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
          secretKey: ${{ secrets.HETZNER_S3_ACCESS_SECRET }}
          bucket: gha-cache-2
          key: ccache-osx-${{ env.VALHALLA_BRANCH }}
          path: ~/Library/Caches/ccache

      - name: Run Tests
        run: make -C build -j$(sysctl -n hw.logicalcpu) check

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ env.SETUP_TMATE == 'true' || failure() }}
        with:
          detached: true
