name: release protobuf generated code

on:
  push:
    branches: [master]
    tags: ["*"]
 
defaults:
  run:
    working-directory: proto
 
jobs:
  release-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install poetry betterproto2[compiler]
      - run: make release-python
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.TESTPYPI_TOKEN }}
 
  release-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: make release-ts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
